# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/LearningMaterials/CS202/Project/CS202_Project/CS202_Project/CS202_Project.srcs/sources_1/ip/programROM/programROM.xci
# IP: The module: 'programROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LearningMaterials/CS202/Project/CS202_Project/CS202_Project/CS202_Project.srcs/sources_1/ip/programROM/programROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'programROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/LearningMaterials/CS202/Project/CS202_Project/CS202_Project/CS202_Project.srcs/sources_1/ip/programROM/programROM.xci
# IP: The module: 'programROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/LearningMaterials/CS202/Project/CS202_Project/CS202_Project/CS202_Project.srcs/sources_1/ip/programROM/programROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'programROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
