# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/CPU.xdc

# IP: ip/programROM/programROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==programROM || ORIG_REF_NAME==programROM} -quiet] -quiet

# IP: ip/cpu_clk/cpu_clk.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_clk || ORIG_REF_NAME==cpu_clk} -quiet] -quiet
